version: '3.7'

services:
  jenkins:
    build: .
    ports:
    - target: 8080
      published: 8080
    volumes:
    - type: bind
      source: ./jenkins/home
      target: /var/jenkins_home
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
